name: CMake on a single platform

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y cmake make gcc g++ libboost-all-dev libpcl-dev libopencv-dev



      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake make gcc g++ git libboost-all-dev libpcl-dev \
            libeigen3-dev libglfw3-dev libjpeg-dev libpng-dev libtiff-dev \
            libglew-dev liblz4-dev libopenmpi-dev libxrandr-dev

      - name: Install GTSAM from source
        run: |
          git clone --branch develop https://github.com/borglab/gtsam.git
          cd gtsam
          mkdir build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release
          make -j$(nproc)
          sudo make install

#      - name: Install GTSAM
#        run: git clone --single-branch --branch develop https://github.com/borglab/gtsam.git && mkdir build && cd build && cmake .. && make install

#      - name: Install GTSAM from source
#        run: |
#          git clone --branch 4.2a5 https://github.com/borglab/gtsam.git
#          cd gtsam
#          mkdir build
#          cd build
#          cmake .. -DCMAKE_BUILD_TYPE=Release
#          make -j$(nproc)
#          sudo make install

      - name: Install open3D
        run: |
          git clone --branch v0.17.0 https://github.com/isl-org/Open3D.git
          cd Open3D
          mkdir build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release \
                   -DBUILD_SHARED_LIBS=ON \
                   -DBUILD_CUDA_MODULE=OFF \
                   -DBUILD_UNIT_TESTS=OFF \
                   -DBUILD_EXAMPLES=OFF
          make -j$(nproc)
          sudo make install
        #run: wget -c https://github.com/intel-isl/Open3D/releases/download/v0.12.0/open3d-app-0.12.0-Ubuntu_20.04.deb && sudo apt-get install ./open3d-app-0.12.0-Ubuntu_20.04.deb
        # Add other dependencies if required

      - name: Configure CMake
        run: cmake -B build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Build
        run: cmake --build build --config ${{env.BUILD_TYPE}}

      - name: Test
        working-directory: build
        run: ctest -C ${{env.BUILD_TYPE}} --output-on-failure # Adds verbosity to show failing test output
