name: CMake on a single platform

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release
  GTSAM_DIR: /usr/local/lib/cmake/GTSAM
  TBB_ROOT_DIR: /usr/include/tbb # or wherever your TBB is installed
  TBB_LIBRARY: /usr/lib/x86_64-linux-gnu/libtbb.so  # or wherever your TBB library is installed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y cmake make gcc g++ libboost-all-dev libpcl-dev libopencv-dev libyaml-cpp-dev

      - name: Install additional dependencies, including TBB
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake make gcc g++ git libboost-all-dev libpcl-dev \
            libeigen3-dev libglfw3-dev libjpeg-dev libpng-dev libtiff-dev \
            libglew-dev liblz4-dev libopenmpi-dev libxrandr-dev libxinerama-dev libtbb-dev

      - name: Export TBB paths
        run: |
          echo "TBB_ROOT_DIR=/usr/include/tbb" >> $GITHUB_ENV
          echo "TBB_LIBRARY=/usr/lib/x86_64-linux-gnu/libtbb.so" >> $GITHUB_ENV

      - name: Install GTSAM from source
        run: |
          git clone --branch 4.0.3 https://github.com/borglab/gtsam.git
          cd gtsam
          mkdir build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release -DTBB_ROOT_DIR=${{ env.TBB_ROOT_DIR }} -DTBB_LIBRARY=${{ env.TBB_LIBRARY }}
          make -j$(nproc)
          sudo make install

      - name: Install ISPC
        run: |
          wget https://github.com/ispc/ispc/releases/download/v1.24.0/ispc-v1.24.0-linux.tar.gz
          tar -xzf ispc-v1.24.0-linux.tar.gz
          sudo cp ispc-v1.24.0-linux/bin/ispc /usr/local/bin/

      - name: Clone Open3D repository
        run: git clone https://github.com/isl-org/Open3D

      - name: Install Open3D dependencies
        working-directory: Open3D
        run: util/install_deps_ubuntu.sh

      - name: Configure Open3D
        working-directory: Open3D
        run: |
          mkdir build
          cd build
          cmake .. -DCMAKE_INSTALL_PREFIX=$HOME/open3d_install -DBUILD_PYTHON_MODULE=OFF -DISPC_EXECUTABLE=/usr/local/bin/ispc -Wno-dev

      - name: Build Open3D
        working-directory: Open3D/build
        run: make -j$(nproc)

      - name: Install Open3D C++ library
        working-directory: Open3D/build
        run: sudo make install

      - name: Set Open3D CMake path
        run: echo "Open3D_DIR=$HOME/open3d_install/lib/cmake/Open3D" >> $GITHUB_ENV

      - name: Configure CMake for the project
        run: cmake -B build -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} -DGTSAM_DIR=${{ env.GTSAM_DIR }} -DOpen3D_DIR=${{ env.Open3D_DIR }}

      - name: Build the project
        run: cmake --build build --config ${{ env.BUILD_TYPE }}

      - name: Test the project
        working-directory: build
        run: ctest -C ${{ env.BUILD_TYPE }} --output-on-failure